### ISSUE TITLE
Adding and editing manually variables

### ISSUE THREAD

**Issue by Lazzeking** [CurlerRoo/CurlerRoo#1]
Hi,
have been using CurlerRoo for a few days by now and I noticed that multiple times I'm in need of inserting manually a variable because i use it multiple times in various calls or maybe sometimes i just straight up edit it, for now i've been using a before script on the top of the project but that seems more like a "cheat" if you know what i mean.

Adding manually and editing variables could be a nice feature to have.

**Comment by CurlerRoo** [comment]
Hi @Lazzeking. 

Thanks for using CurlerRoo and the suggestion. I really appreciate it.

I've just released a new version, which you can find at https://github.com/CurlerRoo/CurlerRoo/releases/tag/v0.2.0. 

This version includes new buttons for editing and adding variables. You can use Settings -> Check for updates to get the update, or simply download it directly.
